<?php

namespace Biblioteca\DemoBundle\Entity;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityRepository;
use Biblioteca\DemoBundle\Entity\Biblioteca;
use Biblioteca\DemoBundle\Entity\BibliotecaRepository;
use Biblioteca\DemoBundle\Entity\Libro;
use Biblioteca\DemoBundle\Entity\LibroRepository;


/**
 * BibliotecaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BibliotecaRepository extends EntityRepository
{
    public function eliminarBiblioteca($id) {
        $em = $this->getEntityManager();
        $biblioteca = $this->find($id);
        $libros= $em->getRepository('BibliotecaDemoBundle:Libro')->findBy(['biblioteca' => $biblioteca]);
        foreach ($libros as $libro) {
            $em->remove($libro);
        }
        $em->remove($biblioteca);
        $em->flush();
    }
}
