<?php

namespace Biblioteca\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LibroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LibroRepository extends EntityRepository
{
    public function listarLibrosBiblioteca($idBiblioteca)
    {
        $em = $this->getEntityManager();
        $biblioteca = $em->getRepository('BibliotecaDemoBundle:Biblioteca')->find($idBiblioteca);
        $libros = $em->getRepository($this->getEntityName())->findBy(['biblioteca' => $biblioteca]);
        return $libros;
    }
    public function librosTituloBiblioteca($idBiblioteca,$titulo)
    {
        $em = $this->getEntityManager();
        $biblioteca = $em->getRepository('BibliotecaDemoBundle:Biblioteca')->find($idBiblioteca);
        $libros = $em->getRepository($this->getEntityName())->findBy([
            'titulo' => $titulo,
            'biblioteca' => $biblioteca
        ]);
        return $libros;
    }
    public function librosAutorBiblioteca($idBiblioteca,$autor)
    {
        $em = $this->getEntityManager();
        $biblioteca = $em->getRepository('BibliotecaDemoBundle:Biblioteca')->find($idBiblioteca);
        $libros = $em->getRepository($this->getEntityName())->findBy([
            'autor' => $autor,
            'biblioteca' => $biblioteca
        ]);
        return $libros;
    }
    public function librosEditorialBiblioteca($idBiblioteca,$editorial)
    {
        $em = $this->getEntityManager();
        $biblioteca = $em->getRepository('BibliotecaDemoBundle:Biblioteca')->find($idBiblioteca);
        $libros = $em->getRepository($this->getEntityName())->findBy([
            'editorial' => $editorial,
            'biblioteca' => $biblioteca
        ]);
        return $libros;
    }
    
}
